In [1]:
import numpy as np

In [5]:
fitness_data = np.array([
    [5000, 200, 6],
    [7000, 250, 7],
    [6500, 230, 6],
    [8000, 300, 8],
    [9000, 320, 7],
    [7500, 270, 6],
    [12000, 400, 5]
])
print(fitness_data)

[[ 5000   200     6]
 [ 7000   250     7]
 [ 6500   230     6]
 [ 8000   300     8]
 [ 9000   320     7]
 [ 7500   270     6]
 [12000   400     5]]


In [7]:
#Get the dimensions of the array
dimensions = fitness_data.ndim
print("Dimensions of the array:", dimensions)

Dimensions of the array: 2


In [8]:
#Get the shape of the array
shape=fitness_data.shape
print("Shape of the array:", shape)

Shape of the array: (7, 3)


In [9]:
# the total number of elements 
total_number = fitness_data.size
print("Total number of elements in the array:", total_number)

Total number of elements in the array: 21


In [11]:
#slice the all step values
step_values =fitness_data[:,1]
step_values


array([200, 250, 230, 300, 320, 270, 400])

In [13]:
#slice the all calories burned 
calories_burned = fitness_data[:,0] 
calories_burned

array([ 5000,  7000,  6500,  8000,  9000,  7500, 12000])

In [14]:
#slice all sleep values
sleep_values = fitness_data[:,2]
sleep_values

array([6, 7, 6, 8, 7, 6, 5])

In [15]:
#Get the first three days 
first_three_days = fitness_data[:3]
first_three_days

array([[5000,  200,    6],
       [7000,  250,    7],
       [6500,  230,    6]])

In [16]:
# Get the steps and calories only
steps_and_calories =fitness_data[:, :2]
steps_and_calories

array([[ 5000,   200],
       [ 7000,   250],
       [ 6500,   230],
       [ 8000,   300],
       [ 9000,   320],
       [ 7500,   270],
       [12000,   400]])

In [18]:
#Reshape the data 
# Reshape the steps array into a column (7,1)
reshaped_steps = step_values.reshape(-1, 1)
reshaped_steps

array([[200],
       [250],
       [230],
       [300],
       [320],
       [270],
       [400]])

In [20]:
#Reshape the full dataset into shape (3,7)
reshaped_fitness_data = fitness_data.reshape(3, 7)
reshaped_fitness_data

array([[ 5000,   200,     6,  7000,   250,     7,  6500],
       [  230,     6,  8000,   300,     8,  9000,   320],
       [    7,  7500,   270,     6, 12000,   400,     5]])

In [ ]:
#Find the days with more than 8000 steps
high_steps = fitness_data[fitness_data[:, 0] > 8000]
print(high_steps)

[[ 9000   320     7]
 [12000   400     5]]


In [ ]:
#Find Days where sleep is less than 6 hours
low_sleep = fitness_data[fitness_data[:, 2] < 6]
print(low_sleep)


[[12000   400     5]]


In [25]:
#Find Days where calories are greater than 300
high_calories = fitness_data[fitness_data[:, 1] > 300]
print(high_calories)

[[ 9000   320     7]
 [12000   400     5]]


In [27]:
#Get the avarage steps
average_steps = np.mean(fitness_data[:, 0])
average_steps

np.float64(7857.142857142857)

In [28]:
#Get the Maximum steps
maximum_steps = np.max(fitness_data[:, 0])
maximum_steps

np.int64(12000)

In [29]:
#Find Minimum sleep hours
minimum_sleep = np.min(fitness_data[:, 2])
minimum_sleep


np.int64(5)

In [31]:
#Find Standard deviation of calories
standard_deviation_calories = np.std(fitness_data[:, 1])
standard_deviation_calories


np.float64(61.278887398649196)

In [32]:
#Find Range of steps
range_steps = np.max(fitness_data[:, 0]) - np.min(fitness_data[:, 0])
range_steps

np.int64(7000)

## Fitness Data Insights

The average number of steps is approximately 7,786 steps per day. The maximum number of steps is 12,000, while the minimum number of steps is 5,000, giving a step range of 7,000.

The data shows that days with a higher number of steps generally have higher calories burned. For example, the day with 12,000 steps also has the highest calorie burn of 400 calories.

Day 7 appears unusual because it has the highest number of steps and calories burned but the lowest amount of sleep at only 5 hours.

The standard deviation of calories is approximately 62.73, which indicates that calorie burn varies across the seven days.

From this data, I learned how NumPy matrices can be used to slice, reshape, filter, and statistically analyze fitness data. I also noticed a possible positive relationship between physical activity and calories burned.
